In [2]:
import numpy as np
arr = np.array([1,2,3])
print(arr)


[1 2 3]


In [3]:
arr1[2]

<class 'NameError'>: name 'arr1' is not defined

In [4]:
arr[2]

3

In [5]:
arr[2]=5

In [6]:
arr

array([1, 2, 5])

In [7]:
arr2=np.array([[1,2,3],[4,5,6]]
print(arr2)

<class 'SyntaxError'>: '(' was never closed (<ipython-input-7-0210bf46363c>, line 1)

In [8]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
print("the shape is 2 rows and 3 column:",arr2.shape)

the shape is 2 rows and 3 column: (2, 3)


In [10]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [11]:
arr3=np.array(['India','China','USA','Mexico'])

In [12]:
arr3

array(['India', 'China', 'USA', 'Mexico'], dtype='<U6')

In [13]:
arr3[1]

'China'

In [14]:
arr3[3]


'Mexico'

In [15]:
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [16]:
arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
arr=np.array([1,2,3,4])

In [18]:
arr

array([1, 2, 3, 4])

In [19]:
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
arr=np.linspace(0.10,20)
print(arr)

[ 0.1         0.50612245  0.9122449   1.31836735  1.7244898   2.13061224
  2.53673469  2.94285714  3.34897959  3.75510204  4.16122449  4.56734694
  4.97346939  5.37959184  5.78571429  6.19183673  6.59795918  7.00408163
  7.41020408  7.81632653  8.22244898  8.62857143  9.03469388  9.44081633
  9.84693878 10.25306122 10.65918367 11.06530612 11.47142857 11.87755102
 12.28367347 12.68979592 13.09591837 13.50204082 13.90816327 14.31428571
 14.72040816 15.12653061 15.53265306 15.93877551 16.34489796 16.75102041
 17.15714286 17.56326531 17.96938776 18.3755102  18.78163265 19.1877551
 19.59387755 20.        ]


In [22]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [23]:
print(np.full((4,6),1))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [25]:
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [26]:
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [27]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
arr=np.random.rand(5,5)
print(arr)


[[0.6588274  0.86654091 0.98247311 0.78054209 0.83676642]
 [0.71863235 0.23915774 0.08856033 0.49043326 0.28120643]
 [0.24666543 0.86839209 0.77346088 0.13195698 0.70398224]
 [0.73596472 0.29868947 0.74826898 0.82517448 0.23068178]
 [0.17311325 0.96756802 0.25442801 0.66277263 0.37817695]]


In [30]:
print(np.sum(arr,axis=0))

[2.53320314 3.24034824 2.84719131 2.89087943 2.43081381]


In [31]:
print(np.sum(arr,exis=1))

<class 'TypeError'>: _sum_dispatcher() got an unexpected keyword argument 'exis'

In [32]:
print(np.sum(arr,axis=1))

[4.12514992 1.81799012 2.72445762 2.83877943 2.43605885]


In [33]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.557697437678312
0.6627726255644236
0.28630745395337165
0.08197195818926203


In [34]:
arr=np.random.rand(5,5)
print(arr)

[[0.93685838 0.1860863  0.12652202 0.77460822 0.99115922]
 [0.38569301 0.59541852 0.45262694 0.80238636 0.19877172]
 [0.03388797 0.4603231  0.26713048 0.88351937 0.34491501]
 [0.53554817 0.9438595  0.14177914 0.28917854 0.28585708]
 [0.12992041 0.43943891 0.08955581 0.62439329 0.38853241]]


In [35]:
print(np.sort(arr,axis=1))

[[0.12652202 0.1860863  0.77460822 0.93685838 0.99115922]
 [0.19877172 0.38569301 0.45262694 0.59541852 0.80238636]
 [0.03388797 0.26713048 0.34491501 0.4603231  0.88351937]
 [0.14177914 0.28585708 0.28917854 0.53554817 0.9438595 ]
 [0.08955581 0.12992041 0.38853241 0.43943891 0.62439329]]


In [36]:
rint(np.sum(arr,axis=1))

In [37]:
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [38]:
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [39]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8,]])

In [40]:
cat=np.concatenate((arr1,arr2),axis=0)

In [41]:
print(cat)


[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [42]:
cat=np.concatinate((arr1,arr2)axis=1)
print(cat)

<class 'SyntaxError'>: invalid syntax. Perhaps you forgot a comma? (<ipython-input-42-2e7618570c48>, line 1)

In [43]:
cat=np.concatenate((arr1,arr2)axis=1)
print(cat)

<class 'SyntaxError'>: invalid syntax. Perhaps you forgot a comma? (<ipython-input-43-7387f8821e87>, line 1)

In [44]:
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
